[project]
name = "lambda-sample-ecs"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["aws-lambda-powertools[aws-sdk]>=3.11.0"]
