name: update-lambda-function-code
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-lambda-code:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save current version
        run: |
          echo "VERSION=v$(utils/get_current_version.sh)" >> $GITHUB_ENV

      - name: Check version
        run: echo "${VERSION}"

      - name: Check head_ref
        run: echo "${{ github.head_ref }}"

      - name: Check if merged
        run: |
          echo "merged: ${{ github.event.pull_request.merged }}"

      - name: Store if continue of not
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" && "${{ github.head_ref }}" == "${VERSION}" ]]; then
            echo "continue=true" >> $GITHUB_ENV
          else
            echo "continue=false" >> $GITHUB_ENV
          fi

      - name: Build Image
        if: env.continue == 'true'
        run: |
          docker buildx build --platform linux/amd64 --provenance=false -t "${{ secrets.IMAGE_NAME }}":"${VERSION}" .

      - name: Configure AWS credentials
        if: env.continue == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Store Registory URI
        if: env.continue == 'true'
        run: |
          echo "REGISTRY_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com" >> $GITHUB_ENV

      - name: Store Image URI
        if: env.continue == 'true'
        run: |
          echo "IMAGE_URI=${REGISTRY_URI}/${{ secrets.REPO_NAME }}:latest" >> $GITHUB_ENV

      - name: Add new tag
        if: env.continue == 'true'
        run: |
          docker tag "${{ secrets.IMAGE_NAME }}:${VERSION}" "${IMAGE_URI}"

      - name: Push to ECR
        if: env.continue == 'true'
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin "${REGISTRY_URI}"
          docker push "${IMAGE_URI}"

      - name: Update Lambda function
        if: env.continue == 'true'
        run: |
          aws lambda update-function-code --function-name "${{ secrets.FUNCTION_NAME }}" --image-uri "${IMAGE_URI}" --publish

      - name: Configure git
        if: env.continue == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "gha@example.com"

      - name: Add new tag
        if: env.continue == 'true'
        run: |
          git tag "${VERSION}"
          git push origin "${VERSION}"
